"""LLM generation default sampling parameters."""

__all__ = [
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_TOP_P",
    "DEFAULT_FREQUENCY_PENALTY",
    "DEFAULT_PRESENCE_PENALTY",
    "DEFAULT_MIN_P",
    "DEFAULT_TOP_K",
    "DEFAULT_TOP_LOGPROBS",
    "MIN_TOP_LOGPROBS",
    "MAX_TOP_LOGPROBS",
]

DEFAULT_MAX_TOKENS = 8192
DEFAULT_TEMPERATURE = 0.7
DEFAULT_TOP_P = 0.9
DEFAULT_FREQUENCY_PENALTY = 0.0
DEFAULT_PRESENCE_PENALTY = 0.0

# Advanced sampling parameters (OPP-26)
DEFAULT_MIN_P = None
DEFAULT_TOP_K = None

# Log-probabilities (OPP-29)
DEFAULT_TOP_LOGPROBS = 1
MIN_TOP_LOGPROBS = 1
MAX_TOP_LOGPROBS = 20
